// routes/Search.js
const express = require('express');
const router = express.Router();
const fs = require('fs');

// Load JSON generated by Python
let rawData;
try {
  rawData = fs.readFileSync('data.json');
} catch (err) {
  console.error("⚠️ data.json not found. Run excel_to_json.py first.");
  rawData = "{}";
}
let jsonData = JSON.parse(rawData);

// Search endpoint
router.get('/search', (req, res) => {
  try {
    const { q } = req.query;
    if (!q) return res.json([]);

    const searchTerm = q.toLowerCase();
    let results = [];

    // Search through all sheets and rows
    for (let sheet in jsonData) {
      jsonData[sheet].forEach((row) => {
        if (
          Object.values(row).some((val) =>
            String(val).toLowerCase().includes(searchTerm)
          )
        ) {
          results.push({ sheet, ...row });
        }
      });
    }

    res.json(results.slice(0, 10)); 
  } catch (err) {
    console.error("❌ Search error:", err);
    res.status(500).json({ error: "Search failed" });
  }
});

module.exports = router;
